# Generated by Django 5.2 on 2026-05-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('musica', 'Musiquinhas'), ('historias', 'Histórias & Fauna'), ('alfabetizacao', 'Alfabetização'), ('desenvolvimento', 'Coordenação e Brincar')], max_length=30)),
                ('youtube_url', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=255)),
                ('cover_image', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('activity_title', models.CharField(max_length=200)),
                ('activity_materials', models.TextField()),
                ('activity_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_videosubmission',
            },
        ),
    ]
